# Generated by Django 2.1.2 on 2019-04-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_api', '0003_auto_20190416_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='pattern',
        ),
        migrations.AddField(
            model_name='play',
            name='hosts',
            field=models.CharField(default='all', max_length=1024, verbose_name='Hosts'),
        ),
    ]
