# Generated by Django 2.1.2 on 2018-12-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offline',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
