# Generated by Django 2.1.2 on 2018-12-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0003_auto_20181225_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offline',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
