# Generated by Django 2.1.2 on 2018-12-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openshift_api', '0004_auto_20181225_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offline',
            old_name='content',
            new_name='content_yml',
        ),
    ]
